### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by manuscle** [dart-lang/reflectable#159]
Is that possible to upgrade package version dependencies?
When I try to install, I get this error:
The current Dart SDK version is 2.1.0.

```
Because reflectable >=2.0.2 <2.0.8 depends on build ^0.12.0 and reflectable >=2.0.8 depends on analyzer ^0.33.0, reflectable >=2.0.2 requires build ^0.12.0 or analyzer ^0.33.0.
And because angular >=5.2.0 depends on analyzer ^0.34.0 and build_runner >=1.0.0 depends on build >=1.0.0 <1.1.0, one of build_runner >=1.0.0 or reflectable >=2.0.2 or angular >=5.2.0 must be false.
And because reflectable <2.0.2 requires SDK version >=1.8.0 <2.0.0-dev.infinity and agde_mobilite_web depends on angular ^5.2.0, build_runner >=1.0.0 is incompatible with reflectable.
So, because agde_mobilite_web depends on both reflectable any and build_runner ^1.1.2, version solving failed.
```
My pubspec.yaml file:
```
name: my_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  http: ^0.11.0
  stream_transform: ^0.0.6
  angular_components: ^0.10.1
#  sass_builder:
    # This is a temporary work around to have sass_builder include node_modules
    # when it looks for .scss files. The workaround will no longer be needed
    # when https://github.com/dart-league/sass_builder/pull/47 is released.
#    git: https://github.com/jifalops/sass_builder
  sass_builder: ^2.0.2
  intl: ^0.15.7
  cookie_jar: ^0.0.7
  dio:
#  slickdart:
#  mdc_web:
#  ng_bootstrap: ^1.1.1
  bootstrap_sass: ^4.1.3
  crypto:
  uuid: ^1.0.3
  reflectable:

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.1.2
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
  coverage: ^0.12.3
  mockito: ^3.0.0-beta+1
  pageloader: ^3.0.3
#  intl_translation:
  json_serializable: ^2.0.1
  # grinder is as Dart workflows, automated lib
  grinder:
  path:
```
