### ISSUE TITLE
Error when customize build.yaml

### ISSUE THREAD

**Issue by manuscle** [dart-lang/reflectable#162]
Hi, when I customize build.yaml file to specify on which folder I would like reflectable work, I get some errors at build time:

```
targets:
  $default:
    sources:
      include: ["lib/**", "web/**", "test/**"]
      exclude:
        - web/nodes_modules/**
    builders:
      build_web_compilers|entrypoint:
        release_options:
          dart2js_args:
            - -DwcfHost=xxxxxxx
      sass_builder:
        release_options:
          outputStyle: compressed
      reflectable:
        generate_for:
          - lib/src/**.dart
          - web/main.dart
#          - test/**_test.dart
        options:
          formatted: true
```

Error reported:
```
[SEVERE] reflectable on lib/src/etablissement/etablissement_search.g.dart:

Asset [agde_mobilite_web|lib/src/etablissement/etablissement_search.g.dart] is not a Dart library. It may be a part file or a file without Dart source code.
[SEVERE] reflectable on lib/src/etablissement/etablissement.g.dart:

Asset [agde_mobilite_web|lib/src/etablissement/etablissement.g.dart] is not a Dart library. It may be a part file or a file without Dart source code.
[SEVERE] reflectable on lib/src/mixins/paginer.g.dart:

Asset [agde_mobilite_web|lib/src/mixins/paginer.g.dart] is not a Dart library. It may be a part file or a file without Dart source code.
[SEVERE] reflectable on lib/src/wcf/wcf_paging.g.dart:
```
I'm using json_serializable and it seems to try reflect files before the *.g.dart files generation. Is the a way to resolve this?

**Comment by zoechi** [comment]
I'd try deleting `.dart-tool/build` and run again

**Comment by manuscle** [comment]
Still get errors

**Comment by zoechi** [comment]
The same errors?

**Comment by manuscle** [comment]
Yes, exactly the same

**Comment by eernstg** [comment]
Maybe you don't actually want to specify `lib/src/**.dart` in `generate_for`. The reflectable code generation approach is inherently working on a whole program, so you should specify exactly the libraries which are entry points, that is, roughly, libraries that contain a `main` function and that you're thinking about as "programs".

So you'd presumably include `lib/main.dart` in the context of a Flutter package, and nothing else.

All libraries which are directly or indirectly imported from your entry points will be taken into account because they'll be inspected during code generation. All results from this process will be expressed as a single generated file (here: `lib/main.reflectable.dart`, which would be imported by `lib/main.dart`), and that file contains elements which are used in the support of reflection on instances and types from all the reachable libraries.

**Comment by manuscle** [comment]
Oh ok, I got it! I did not understand the concept of the entry point when I've read the doc.
So in my case including lib/src/** is useless. I removed that line and everything working fine now
Thanks a lot @eernstg !

**Comment by HerrNiklasRaab** [comment]
> Maybe you don't actually want to specify `lib/src/**.dart` in `generate_for`. The reflectable code generation approach is inherently working on a whole program, so you should specify exactly the libraries which are entry points, that is, roughly, libraries that contain a `main` function and that you're thinking about as "programs".
> 
> So you'd presumably include `lib/main.dart` in the context of a Flutter package, and nothing else. Maybe there's another entry point in `bin` and some in `test`, and then you can include them as well, but it should still only be entry points.
> 
> All libraries which are directly or indirectly imported from your entry points will be taken into account because they'll be inspected during the analysis and code generation steps of reflectable. All results from this process will be expressed as a single generated file (here: `lib/main.reflectable.dart`, which would be imported by `lib/main.dart`), and that file contains elements which are used in the support of reflection on instances and types from all the reachable libraries.
> 
> If you do this, you'd presumably stop seeing messages about libraries in `lib/src/**` (but if they are part files then you'll get access to the declarations in there because they will be loaded as such during the analysis phase).

@eernstg How do I handle this, in my test project? I have hundreds of test files, who are all having a `main()` function. Do I need to generate a reflectable for every of those hundred test files?

To have multiple `main()` functions in multiple test files, seems to be the go-to, since the flutter example projects are written like this: https://github.com/flutter/flutter/tree/master/examples/catalog/test

**Comment by eernstg** [comment]
It should not be a problem to generate a '*.reflectable.dart' file for each of those hundreds of test files, and it might be possible for you to select the entry points using a wildcard or two:

```yaml
// build.yaml
targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - test/**_test.dart
```

This will work if all your entry points have a name ending in `_test.dart` and none of the other files in that directory has a name of that form. Maybe you could use that directly, or adjust some file names such that it will work?
