### ISSUE TITLE
dependency resolving

### ISSUE THREAD

**Issue by e-belair** [dart-lang/reflectable#175]
Hi, since a recent update of sdk to 2.3 I had to upgrade build_runner and build_web_compilers.
Now I can't figure out with this dependency version error:
```
/usr/lib/dart/bin/pub upgrade
Resolving dependencies...
Because reflectable >=2.0.10 depends on build_runner_core >=1.0.0 <3.0.0 and build_runner >=1.3.0 depends on build_runner_core ^3.0.0, reflectable >=2.0.10 is incompatible with build_runner >=1.3.0.
So, because agde_mobilite_web depends on both reflectable ^2.0.12 and build_runner ^1.3.0, version solving failed.
Process finished with exit code 1
```
pubspec.yml file:
```
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  http: ^0.11.0
  stream_transform: ^0.0.6
  angular_components: ^0.10.1
  sass_builder: ^2.0.2
  bulma_sass: ^0.7.1+1
  intl: ^0.15.7
  cookie_jar: ^0.0.7
  dio:
  mdc_web:
  crypto:
  uuid: ^1.0.3
  reflectable: ^2.0.12
  recase:

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.3.0
  build_test: ^0.10.2
  build_web_compilers: ^2.0.0
  built_html: ^0.1.0
  test: ^1.0.0
  coverage: ^0.12.3
  mockito: ^3.0.0-beta+1
  pageloader: ^3.0.3
  json_serializable: ^2.0.1
  grinder:
  path:
```
How can I resolve this issue?
