### ISSUE TITLE
Webdev serve Reflecting on type 'xxxx' without capabilities

### ISSUE THREAD

**Issue by e-belair** [dart-lang/reflectable#186]
When I run `pub global run webdev serve web:53322` for the first time or randomly
I get the following error: `Reflecting on type 'xxxx' without capabilities`

I need to run (again) `pub global run webdev build --output=web:build` and re-run webdev serve to get the reflecting correctly builded.

```yaml
targets:
  $default:
    sources:
      include: ["lib/**", "web/**", "test/**", "pubspec.yaml"]
      exclude:
        - web/nodes_modules/**
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - test/**_test.dart
          - web/**.dart
        release_options:
          dart2js_args:
            - --fast-startup
            - --minify
            - -Dhost=/api/wcf
      sass_builder:
        release_options:
          outputStyle: compressed
      reflectable:
        generate_for:
          - web/main.dart
          - test/**_test.dart
        options:
          formatted: true
```

dart 2.4
reflectable 2.1.0
